version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(localhost)
